title: DiO 
description: Decentralization in Organizations
theme: just-the-docs
url: dio-community.org
aux_links:
  "DiO on GitHub": 
    - "https://github.com/linxule/dio"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Logo and favicon
logo: "/asset/logo.png"
favicon_ico: "/asset/icon.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# External navigation links
#nav_external_links:
#  - title: Just the Docs on GitHub
#    url: https://github.com/just-the-docs/just-the-docs
#    hide_icon: false # set to true to hide the external link icon - defaults to false
#    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
