title: DiO 
description: Decentralization in Organizations
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

url: https://just-the-docs.github.io

aux_links:
  GitHub Repository: https://github.com/linxule/dio
